import type { ProfileKey } from '~/types'

export const ALIAS_MAP: Record<string, ProfileKey> = {
  firstname: 'firstName',
  fname: 'firstName',
  givenname: 'firstName',
  lastname: 'lastName',
  lname: 'lastName',
  surname: 'lastName',
  fullname: 'fullName',
  email: 'email',
  emailaddress: 'email',
  useremail: 'email',
  phone: 'phone',
  mobile: 'phone',
  mobilenumber: 'phone',
  contactnumber: 'phone',
  phonenumber: 'phone',
  address: 'address',
  addr: 'address',
  street: 'address',
  city: 'city',
  state: 'state',
  country: 'country',
  pincode: 'pincode',
  zip: 'pincode',
  zipcode: 'pincode',
  postal: 'pincode',
  postcode: 'pincode',
  linkedin: 'linkedin',
  github: 'github',
  portfolio: 'portfolio',
  website: 'portfolio',
  college: 'college',
  university: 'college',
  school: 'college',
  degree: 'degree',
  graduationyear: 'graduationYear',
  gradyear: 'graduationYear',
  yearofgraduation: 'graduationYear',
  company: 'currentCompany',
  currentcompany: 'currentCompany',
  employer: 'currentCompany',
  role: 'currentRole',
  currentrole: 'currentRole',
  jobtitle: 'currentRole',
  designation: 'currentRole',
  resume: 'resumeUrl',
  cv: 'resumeUrl',
  resumeurl: 'resumeUrl',
  curriculumvitae: 'resumeUrl',
}

export const ALIAS_VALUES = Object.keys(ALIAS_MAP)
export const ALIAS_SET = new Set(ALIAS_VALUES)
