import type { Profile } from '~/types'

export const DEFAULT_PROFILE: Profile = {
  title: 'Mr.',
  firstName: 'Raghunandan',
  middleName: 'Rangadorai',
  lastName: 'Kasthuri',
  fullName: 'Raghunandan Rangadorai Kasthuri',
  email: 'ragwhooooo@gmail.com',
  phone: '8050056552',
  fax: '',
  address: '#001 Mbm Omkar Heights, Omkar Nagar, Uttarahalli, Kengeri Main Road',
  city: 'Bangalore',
  state: 'Karnataka',
  country: 'India',
  pincode: '560060',
  linkedin: '',
  github: 'https://github.com/ragwhoo',
  portfolio: 'www.studio-mugen.com',
  college: 'Raja Rajeshwari College of Engineering',
  degree: 'B.Tech',
  graduationYear: '2026',
  currentCompany: '',
  currentRole: '',
  resumeUrl: '',
  userId: '',
  sex: 'Male',
  driversLicense: '',
  age: '22',
  birthPlace: 'Bangalore',
  income: '',
  customMessage: '',
  comments: 'Born on 14th June 2004',
}

export const PROFILE_FIELDS: { key: keyof Profile; label: string; section: string }[] = [
  { key: 'title', label: 'Title', section: 'Personal' },
  { key: 'firstName', label: 'First Name', section: 'Personal' },
  { key: 'middleName', label: 'Middle Name', section: 'Personal' },
  { key: 'lastName', label: 'Last Name', section: 'Personal' },
  { key: 'fullName', label: 'Full Name', section: 'Personal' },
  { key: 'email', label: 'Email', section: 'Contact' },
  { key: 'phone', label: 'Phone', section: 'Contact' },
  { key: 'fax', label: 'Fax', section: 'Contact' },
  { key: 'address', label: 'Address', section: 'Location' },
  { key: 'city', label: 'City', section: 'Location' },
  { key: 'state', label: 'State', section: 'Location' },
  { key: 'country', label: 'Country', section: 'Location' },
  { key: 'pincode', label: 'Pincode', section: 'Location' },
  { key: 'linkedin', label: 'LinkedIn', section: 'Online' },
  { key: 'github', label: 'GitHub', section: 'Online' },
  { key: 'portfolio', label: 'Portfolio', section: 'Online' },
  { key: 'resumeUrl', label: 'Resume URL', section: 'Online' },
  { key: 'college', label: 'College', section: 'Education' },
  { key: 'degree', label: 'Degree', section: 'Education' },
  { key: 'graduationYear', label: 'Graduation Year', section: 'Education' },
  { key: 'currentCompany', label: 'Current Company', section: 'Work' },
  { key: 'currentRole', label: 'Current Role', section: 'Work' },
  { key: 'userId', label: 'User ID', section: 'Personal' },
  { key: 'sex', label: 'Sex', section: 'Personal' },
  { key: 'driversLicense', label: "Driver's License", section: 'Personal' },
  { key: 'age', label: 'Age', section: 'Personal' },
  { key: 'birthPlace', label: 'Birth Place', section: 'Personal' },
  { key: 'income', label: 'Income', section: 'Personal' },
  { key: 'customMessage', label: 'Custom Message', section: 'Personal' },
  { key: 'comments', label: 'Comments', section: 'Personal' },
]

export function isProfile(value: unknown): value is Profile {
  if (typeof value !== 'object' || value === null) return false
  const p = value as Record<string, unknown>
  return PROFILE_FIELDS.every((f) => typeof p[f.key] === 'string')
}
